package com.ultradcr.movie_domain

data class Movie(
	val year: String? = null,
	val directors: String? = null,
	val genreList: List<GenreListItem> = emptyList(),
	val title: String = "",
	val type: String = "",
	val tvEpisodeInfo: Any? = null,
	val imDbRating: String = "",
//	val trailer : Any? = null,
	val runtimeStr: String = "",
	val plotLocal: String = "",
	val companies: String = "",
	val plot: String = "",
	val companyList: List<CompanyListItem>,
	val genres: String = "",
	val actorList: List<ActorListItem>,
	val imDbRatingVotes: String = "",
	val tvSeriesInfo: Any? = null,
	val id: String = "",
//	val languageList: List<LanguageListItem> = emptyList(),
	val image: String = "",
	val fullTitle: String = "",
//	val images: Any? = null,
	val runtimeMins: String = "",
//	val languages: String = "",
	val releaseDate: String = "",
//	val similars: List<SimilarsItem> = emptyList(),
//	val posters: Any? = null,
	val errorMessage: String = "",
//	val metacriticRating: String = "",
	val directorList: List<DirectorListItem> = emptyList(),
	val writers: String = "",
	val stars: String = "",
	val countries: String = "",
//	val countryList: List<CountryListItem> = emptyList(),
//	val plotLocalIsRtl: Boolean = false,
//	val keywordList: List<String> = emptyList(),
	val originalTitle: String = "",
	val awards: String = "",
//	val tagline: String = "",
	val starList: List<StarListItem> = emptyList(),
	val contentRating: String = "",
	val boxOffice: BoxOffice? = null,
	val writerList: List<WriterListItem> = emptyList()
)

